#!/bin/sh

SYSTEMD_EXE="/lib/systemd/systemd --unit=multi-user.target"
SYSTEMD_PID="$(ps -eo pid=,args= | awk '$2" "$3=="'"$SYSTEMD_EXE"'" {print $1}')"
if [ "$LOGNAME" != "root" ] && ( [ -z "$SYSTEMD_PID" ] || [ "$SYSTEMD_PID" != "1" ] ); then
    export | sed -e 's/^declare -x //;/^IFS=".*[^"]$/{N;s/\n//}' | \
        grep -E "^(WT_|WSL_|WSLENV|WSLPATH)" > "$HOME/.systemd-env"
    export SYSTEMD_PRE_NAMESPACE_PATH="$PATH"
    export SYSTEMD_PRE_NAMESPACE_PWD="$PWD"
    exec sudo /usr/sbin/enter-systemd-namespace "$BASH_EXECUTION_STRING"
fi

if [ -n "$SYSTEMD_PRE_NAMESPACE_PATH" ]; then
    export PATH="$SYSTEMD_PRE_NAMESPACE_PATH"
    unset SYSTEMD_PRE_NAMESPACE_PATH
fi
if [ -n "$SYSTEMD_PRE_NAMESPACE_PWD" ]; then
    cd "$SYSTEMD_PRE_NAMESPACE_PWD"
    unset SYSTEMD_PRE_NAMESPACE_PWD
fi
